[development]
address = "localhost"
port = 9001
workers = 8
log = "normal"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[staging]
address = "localhost"
port = 9000
workers = 8
log = "normal"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[production]
address = "localhost"
port = 9000
workers = 8
log = "critical"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }
